add_from_dataset: 0
batch_size: 256
buffer_size: 2000000
checkpoints_path: ./checkpoints/AWAC-halfcheetah-medium-v2-95018c7c
deterministic_torch: false
device: cpu
env_name: halfcheetah-medium-v2
eval_frequency: 1000
gamma: 0.99
group: AWAC-D4RL
hidden_dim: 256
lambda_awac: 1.0
learning_rate: 0.0003
n_test_episodes: 10
name: AWAC-halfcheetah-medium-v2-95018c7c
normalize_reward: false
num_envs: 3
num_train_ops_offline: 2000
num_train_ops_online: 10000
project: CORL
seed: 42
tau: 0.005
test_seed: 69
